version: "3.3"

networks:
  stg-server_central-services:
    external: true

services:
  web-server:
    container_name: webserver-real-estate
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8007:80"
    volumes:
      - ./main/real-estate:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      stg-server_central-services:
            ipv4_address: 172.22.0.22